/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String header = "assets/images/header.jpg";
  static const String iconly_bold = "assets/fonts/iconly_bold.ttf";
  static const String IconlyBroken = "assets/fonts/IconlyBroken.ttf";
  static const String IconlyLight = "assets/fonts/IconlyLight.ttf";
  static const String interconnect = "assets/images/interconnect.png";
  static const String logo = "assets/images/logo.png";
  static const String onBoard = "assets/images/onBoard.jpg";
  static const String onBoard2 = "assets/images/onBoard2.jpg";
  static const String onBoard3 = "assets/images/onBoard3.jpg";
}
